### PR TITLE
issue #35: automate genesis+config generation

### PR DESCRIPTION
**Pull request by nickray**
refs #35

### CODE REVIEW

**Comment by roblav96** [comment]
@nickray This is a great PR!

**Comment by nickray** [comment]
Updated this a bit. The workflow for using it can be seen here: https://github.com/validstate/testnets/tree/inofficial-101/inofficial-101/gaia

Steps for using this (example chain "inofficial-101"):
1. have a Python3 environment with fire and toml libraries installed (e.g. via `pip install -r requirements.txt` or `conda env update -f environment.yaml`)
2. run `python prepare-genesis-inclusion-requests.py inofficial-101` and commit `request.toml.template`
3. have validators submit pull request with `<validator_name>.toml` adapted the template
4. run `python generate-genesis.py inofficial-101` and `python generate-config.py inofficial-101` and commit outputs
5. instruct users how to modify `config.toml` to their needs

I originally planned a config generator for individual validators, but their setups can be too varied to make this really feasible.

@adrianbrink this is what I mentioned in yesterday's call.

**Comment by nickray** [comment]
I have a test of the process running on https://github.com/validstate/testnets/tree/inofficial-101/inofficial-101/gaia/genesis-inclusion-requests

**Comment by amrali** [comment]
This is great, makes the process a lot easier, would love to see this merged.

Thanks @nickray

**Pull request closed without merging**
