### PR TITLE
Add gaia-3005 files based on gaia-3003, 3004, and unofficial-102 for …

### PR DESCRIPTION
**Pull request by krp**
…next weeks launch

requested by @adrianbrink

### CODE REVIEW

**Comment by adrianbrink** [comment]
@krisrp Could you remove all the data besides yours. 

That way everyone has to add their information themself.

**Comment by krp** [comment]
@adrianbrink updated.

**Comment by adrianbrink** [comment]
Awesome.

The only thing is that dns names are currently not supported. Could you replace those with the actual IPs please.

**Comment by krp** [comment]
@adrianbrink DNS for seeds is supported. Myself and a few others have independently tested it (and mentioned it to you a few times in chat).

Any idea approximately when a new gaia is likely to be released, or when it will be merged into cosmos-sdk? I'm leaning towards others' thoughts on this, and considering that running testnet validators may not be worth all the maintenance effort while those fatal bugs that continually bring the testnet down remain unpatched.

**Pull request merged**
